# Generated by Django 4.0.2 on 2022-05-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Adresses'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_adress',
            new_name='billing_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_adress',
            new_name='shipping_address',
        ),
    ]
