# Generated by Django 4.0.2 on 2022-05-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djecommerce', '0002_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
